# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui',
# licensing of 'mainwindow2.ui' applies.
#
# Created: Tue Jun  4 17:10:26 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1148, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblTop = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTop.setFont(font)
        self.lblTop.setScaledContents(True)
        self.lblTop.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTop.setObjectName("lblTop")
        self.verticalLayout_2.addWidget(self.lblTop)
        self.listCourses = QtWidgets.QListWidget(self.centralwidget)
        self.listCourses.setObjectName("listCourses")
        self.verticalLayout_2.addWidget(self.listCourses)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.btnCoursesConf = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCoursesConf.sizePolicy().hasHeightForWidth())
        self.btnCoursesConf.setSizePolicy(sizePolicy)
        self.btnCoursesConf.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnCoursesConf.setFont(font)
        self.btnCoursesConf.setFlat(False)
        self.btnCoursesConf.setObjectName("btnCoursesConf")
        self.horizontalLayout_2.addWidget(self.btnCoursesConf)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblTop_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTop_2.setFont(font)
        self.lblTop_2.setScaledContents(True)
        self.lblTop_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTop_2.setObjectName("lblTop_2")
        self.verticalLayout_3.addWidget(self.lblTop_2)
        self.listQuizzes = QtWidgets.QListWidget(self.centralwidget)
        self.listQuizzes.setObjectName("listQuizzes")
        self.verticalLayout_3.addWidget(self.listQuizzes)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.btnQuizzesConf = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnQuizzesConf.sizePolicy().hasHeightForWidth())
        self.btnQuizzesConf.setSizePolicy(sizePolicy)
        self.btnQuizzesConf.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnQuizzesConf.setFont(font)
        self.btnQuizzesConf.setFlat(False)
        self.btnQuizzesConf.setObjectName("btnQuizzesConf")
        self.horizontalLayout_2.addWidget(self.btnQuizzesConf)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblTop_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTop_3.setFont(font)
        self.lblTop_3.setScaledContents(True)
        self.lblTop_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTop_3.setObjectName("lblTop_3")
        self.verticalLayout_4.addWidget(self.lblTop_3)
        self.listQuestions = QtWidgets.QListWidget(self.centralwidget)
        self.listQuestions.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listQuestions.setObjectName("listQuestions")
        self.verticalLayout_4.addWidget(self.listQuestions)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setEnabled(False)
        self.btnEdit.setObjectName("btnEdit")
        self.horizontalLayout.addWidget(self.btnEdit)
        self.btnRegrade = QtWidgets.QPushButton(self.centralwidget)
        self.btnRegrade.setEnabled(False)
        self.btnRegrade.setObjectName("btnRegrade")
        self.horizontalLayout.addWidget(self.btnRegrade)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1148, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuActions = QtWidgets.QMenu(self.menuBar)
        self.menuActions.setObjectName("menuActions")
        MainWindow.setMenuBar(self.menuBar)
        self.actionLogout = QtWidgets.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionFirefox = QtWidgets.QAction(MainWindow)
        self.actionFirefox.setCheckable(True)
        self.actionFirefox.setChecked(True)
        self.actionFirefox.setObjectName("actionFirefox")
        self.actionChrome = QtWidgets.QAction(MainWindow)
        self.actionChrome.setObjectName("actionChrome")
        self.actionChrome_headless = QtWidgets.QAction(MainWindow)
        self.actionChrome_headless.setObjectName("actionChrome_headless")
        self.menuActions.addAction(self.actionHelp)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionLogout)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionExit)
        self.menuBar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Canvas Regrade Assistant", None, -1))
        self.lblTop.setText(QtWidgets.QApplication.translate("MainWindow", "Select a Course", None, -1))
        self.btnCoursesConf.setText(QtWidgets.QApplication.translate("MainWindow", ">>", None, -1))
        self.lblTop_2.setText(QtWidgets.QApplication.translate("MainWindow", "Select a Quiz", None, -1))
        self.btnQuizzesConf.setText(QtWidgets.QApplication.translate("MainWindow", ">>", None, -1))
        self.lblTop_3.setText(QtWidgets.QApplication.translate("MainWindow", "Select Questions", None, -1))
        self.btnEdit.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Opens a web browser and navigates to the currently selected quiz.", None, -1))
        self.btnEdit.setText(QtWidgets.QApplication.translate("MainWindow", "Edit Quiz", None, -1))
        self.btnRegrade.setText(QtWidgets.QApplication.translate("MainWindow", "Regrade", None, -1))
        self.menuActions.setTitle(QtWidgets.QApplication.translate("MainWindow", "Actions", None, -1))
        self.actionLogout.setText(QtWidgets.QApplication.translate("MainWindow", "Logout", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "Exit", None, -1))
        self.actionHelp.setText(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.actionFirefox.setText(QtWidgets.QApplication.translate("MainWindow", "Firefox", None, -1))
        self.actionChrome.setText(QtWidgets.QApplication.translate("MainWindow", "Chrome", None, -1))
        self.actionChrome_headless.setText(QtWidgets.QApplication.translate("MainWindow", "Chrome (headless)", None, -1))

