# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow2.ui'
#
# Created: Fri Apr 20 17:16:01 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1148, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lblTop = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTop.setFont(font)
        self.lblTop.setScaledContents(True)
        self.lblTop.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTop.setObjectName("lblTop")
        self.verticalLayout_2.addWidget(self.lblTop)
        self.listCourses = QtGui.QListWidget(self.centralwidget)
        self.listCourses.setObjectName("listCourses")
        self.verticalLayout_2.addWidget(self.listCourses)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.btnCoursesConf = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCoursesConf.sizePolicy().hasHeightForWidth())
        self.btnCoursesConf.setSizePolicy(sizePolicy)
        self.btnCoursesConf.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnCoursesConf.setFont(font)
        self.btnCoursesConf.setFlat(False)
        self.btnCoursesConf.setObjectName("btnCoursesConf")
        self.horizontalLayout_2.addWidget(self.btnCoursesConf)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblTop_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTop_2.setFont(font)
        self.lblTop_2.setScaledContents(True)
        self.lblTop_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTop_2.setObjectName("lblTop_2")
        self.verticalLayout_3.addWidget(self.lblTop_2)
        self.listQuizzes = QtGui.QListWidget(self.centralwidget)
        self.listQuizzes.setObjectName("listQuizzes")
        self.verticalLayout_3.addWidget(self.listQuizzes)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.btnQuizzesConf = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnQuizzesConf.sizePolicy().hasHeightForWidth())
        self.btnQuizzesConf.setSizePolicy(sizePolicy)
        self.btnQuizzesConf.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btnQuizzesConf.setFont(font)
        self.btnQuizzesConf.setFlat(False)
        self.btnQuizzesConf.setObjectName("btnQuizzesConf")
        self.horizontalLayout_2.addWidget(self.btnQuizzesConf)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblTop_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTop_3.setFont(font)
        self.lblTop_3.setScaledContents(True)
        self.lblTop_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTop_3.setObjectName("lblTop_3")
        self.verticalLayout_4.addWidget(self.lblTop_3)
        self.listQuestions = QtGui.QListWidget(self.centralwidget)
        self.listQuestions.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.listQuestions.setObjectName("listQuestions")
        self.verticalLayout_4.addWidget(self.listQuestions)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnEdit = QtGui.QPushButton(self.centralwidget)
        self.btnEdit.setEnabled(False)
        self.btnEdit.setObjectName("btnEdit")
        self.horizontalLayout.addWidget(self.btnEdit)
        self.btnRegrade = QtGui.QPushButton(self.centralwidget)
        self.btnRegrade.setEnabled(False)
        self.btnRegrade.setObjectName("btnRegrade")
        self.horizontalLayout.addWidget(self.btnRegrade)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1148, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuActions = QtGui.QMenu(self.menuBar)
        self.menuActions.setObjectName("menuActions")
        MainWindow.setMenuBar(self.menuBar)
        self.actionLogout = QtGui.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionFirefox = QtGui.QAction(MainWindow)
        self.actionFirefox.setCheckable(True)
        self.actionFirefox.setChecked(True)
        self.actionFirefox.setObjectName("actionFirefox")
        self.actionChrome = QtGui.QAction(MainWindow)
        self.actionChrome.setObjectName("actionChrome")
        self.actionChrome_headless = QtGui.QAction(MainWindow)
        self.actionChrome_headless.setObjectName("actionChrome_headless")
        self.menuActions.addAction(self.actionHelp)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionLogout)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionExit)
        self.menuBar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Canvas Regrade Assistant", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTop.setText(QtGui.QApplication.translate("MainWindow", "Select a Course", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCoursesConf.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTop_2.setText(QtGui.QApplication.translate("MainWindow", "Select a Quiz", None, QtGui.QApplication.UnicodeUTF8))
        self.btnQuizzesConf.setText(QtGui.QApplication.translate("MainWindow", ">>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTop_3.setText(QtGui.QApplication.translate("MainWindow", "Select Questions", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEdit.setToolTip(QtGui.QApplication.translate("MainWindow", "Opens a web browser and navigates to the currently selected quiz.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnEdit.setText(QtGui.QApplication.translate("MainWindow", "Edit Quiz", None, QtGui.QApplication.UnicodeUTF8))
        self.btnRegrade.setText(QtGui.QApplication.translate("MainWindow", "Regrade", None, QtGui.QApplication.UnicodeUTF8))
        self.menuActions.setTitle(QtGui.QApplication.translate("MainWindow", "Actions", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogout.setText(QtGui.QApplication.translate("MainWindow", "Logout", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFirefox.setText(QtGui.QApplication.translate("MainWindow", "Firefox", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChrome.setText(QtGui.QApplication.translate("MainWindow", "Chrome", None, QtGui.QApplication.UnicodeUTF8))
        self.actionChrome_headless.setText(QtGui.QApplication.translate("MainWindow", "Chrome (headless)", None, QtGui.QApplication.UnicodeUTF8))

